//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI.CADASTRO.REPOSITORY.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLIENTES()
        {
            this.TB_CLIENTES_ENDERECOS = new HashSet<TB_CLIENTES_ENDERECOS>();
        }
    
        public decimal CLIENTE_ID { get; set; }
        public string CPF { get; set; }
        public string NOME { get; set; }
        public string RG { get; set; }
        public Nullable<System.DateTime> DATA_EXPEDICAO { get; set; }
        public string ORGAO_EXPEDICAO { get; set; }
        public string UF_EXPEDICAO { get; set; }
        public System.DateTime DATA_NASCIMENTO { get; set; }
        public string SEXO { get; set; }
        public string ESTADO_CIVIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CLIENTES_ENDERECOS> TB_CLIENTES_ENDERECOS { get; set; }
    }
}
